from pathlib import Path
import hashlib
from nextai_autoresearch.research_program import status,auxiliary_reserve
from nextai_autoresearch.ledger import append_jsonl
from nextai_autoresearch.utils import load_json,atomic_write_json,sha256_file,utc_now
root=Path.cwd();identity='ASM01-POINT-SERIAL-NATIVE-CONFORMANCE-V1'
path=root/f'research/plans/{identity}.json';assert not path.exists()
directory=f'research/preparations/{identity}';assert not (root/directory).exists()
wallet=status(root);assert wallet['fit_seconds_remaining']-47000>=900 and not wallet['scoring_authorized']
assert wallet['stage_b_registration_attempts_used']==1 and wallet['pending_fit_reservation_seconds']==0
inventory='research/reviews/ASM01-FULL-SCREEN-GRAMMAR-INVENTORY-V3.receipt.json'
old='research/data_manifests/ASM01-ACQUISITION-V3.json';normalizer='research/preparations/ASM01-POINT-SERIAL-PREPARATION-V1/normalizer.py'
assert sha256_file(root/normalizer)=='fbc87c0ba993b73eaa751bc9ecc21cf0fb1ec544887b679cb9c42e8e5f844a8c'
names=['AGENTS.md','config/research.toml','research/state.json','research/eval_manifest.json','research/laboratory/preflight_certificate.json','src/nextai_autoresearch/asm01_task.py','src/nextai_autoresearch/asm01_task_v3.py','src/nextai_autoresearch/asm01_task_v4.py','src/nextai_autoresearch/asm01_inventory_members_v3.py','src/nextai_autoresearch/candidates/asm01_core.py','src/nextai_autoresearch/benchmarks/asm01_native_memory_v2.py','research/plans/ASM01-FROZEN-SOURCE-SCREEN-V3.json',inventory,old,normalizer,'research/laboratory/ASM01-COST-ADMIN-RECONCILIATION-V1.receipt.json']
prefixes={}
for name in ('events.jsonl','sources.jsonl','experiments.tsv'):
 data=(root/'research'/name).read_bytes();prefixes[name]={'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()}
plan={'id':identity,'cycle':332,'created_at':utc_now(),'study_kind':'preparation_only','execution_authority':True,'native_execution_authority':True,'scientific_execution_authority':False,'clock_start':'2026-10-06T03:39:20Z','deadline':'2026-10-06T03:54:20Z','auxiliary_seconds_cap':900,'research_fit_seconds_cap':0,'EXP_cap':0,'registration_cap':0,
 'question':'Can the separately conformed frozen point-serial normalizer preserve exact old74 arrays/all3views and make every fixed1830 native sample geometrically valid without replacement?',
 'prior_turn_classification':'PROGRESS: finite192-call runtime evidence and independently identified budget blockers changed next action; original closing overrun preserved and charged separately. No scientific screening or retry.',
 'scope':{'writers':[1,2,3,4,5,16,17,18,19,20],'samples_each_writer':183,'samples_total':1830,'already_raw_exposed':75,'already_numerically_converted':74,'already_lexically_inventoried':1830,'old_arrays_persisted':False,'future_writers_authorized':False,'source_directory':'research/data/asm01_native_v1/screen-text-v3','listing':'research/data/asm01_native_v1/selected-screen-members-v3.txt','listing_sha256':'d49c97288d650bc42995d27b7301e2b15b4d373b74ec6a320b7971020fe4e4f5','reuse_existing_extraction_only':True,'new_download_or_extraction':False},
 'intake_binding':{'inventory_path':inventory,'inventory_sha256':sha256_file(root/inventory),'old75_path':old,'old75_sha256':sha256_file(root/old),'normalizer_path':normalizer,'normalizer_sha256':sha256_file(root/normalizer),'old_geometry_parser':'nextai_autoresearch.asm01_task_v4.parse_native_sample','new_geometry_parser':'exact oldV4(normalize_release_bytes(raw)); release only, no fallback','publisher_sha256':'d6ad543e65269d53e38fdac6a32dd20bcd942e7616891a6cf95986894b454a4d'},
 'recipe':'Verify fixed1830 metadata/listing/link/alias/byte gates BEFORE payload; W1 samples1..74 first, each read once and SHA matched to both old75 and inventory; parse oldV4 and new-normalizedV4, exact dtype/shape/bytes equality of arrays and write/nominal/adverse views. Only after74/74 PASS open other1756, each inventorySHA and same frozen normalizer->oldV4. Global duplicate check includes each canonical array once. Bounds/dedup/pointcap/arc/RMS/views unchanged. No raw names/coordinates/token emission. Any error stops all unstarted scope, retains attempted hashes and redacted category; no fallback/filter/replacement/retry.',
 'output':'Only after1830/1830 and915D complete, write new sealed preparatory NPZ with points/offsets/rows for all10writers and exact writer/dataset hashes. Not an active loader or scoring dataset; later scientific cohort/task/binding/readiness required. Preserve all old manifests and failures.',
 'implementation_paths':[f'{directory}/intake.py',f'{directory}/test_intake.py'],'fixtures':{'existing38':'research/preparations/ASM01-POINT-SERIAL-PREPARATION-V1/test_normalizer.py','existing38_reason':'All historical protected parent330 bytes remain unchanged; this new standalone preparation reuses the validated normalizer, not a new active cohort integration. Historical fixtures and bindings remain intact.','new8_ids':['complete','old-difference','raw-sha','duplicate','stop-first','future-scope','bindings','clone-origin'],'total':46,'single_pytest_run':True,'fit_in_fixtures':False},
 'metrics':['exact74 oldarrays and all3views','all1830 required identities/hash/geometry valid','global no duplicate array','all46 fixtures PASS','no native output values or names','all protected hashes/prefixes unchanged','single bounded process tree per fixtures and intake, zero live descendants'],
 'thresholds':'Exact equality/complete counts; no filtered fixtures or samples; native failure is INCONCLUSIVE intake, never a learning/transfer/economic null.',
 'process_caps':{'fixtures_seconds':120,'intake_seconds':120,'closing_reserve_seconds':160,'whole_auxiliary900_includes_startup_since03:39:20':True},
 'decision_rule':'KEEP complete native feasibility only if46/46 PASS followed by74/74 exact guards and1830/1830 feasibility without duplicates. Otherwise preserve INCOMPLETE/INVALID exact intake and stop unstarted scope. No same-cycle parser/geometry/source/schema rescue. No fit/EXP/scoring even on PASS.',
 'scientific_prospective_binding':{'source_study_path':'research/plans/ASM01-FROZEN-SOURCE-SCREEN-V3.json','source_study_sha256':sha256_file(root/'research/plans/ASM01-FROZEN-SOURCE-SCREEN-V3.json'),'all_models_source_states_geometry_grids_metrics_thresholds_and45roles810trials_unchanged':True,'recipe_and_gates':{k:load_json(root/'research/plans/ASM01-FROZEN-SOURCE-SCREEN-V3.json')[k] for k in ('matrix','recipe','diagnostics','diagnosis_gates','reference_gates','decision_policy')},'authority':'This preparation freezes future scientific recipe before new native bytes but grants no future EXP authority. Original failed study not reactivated. Future new lower full-cost scope must independently freeze budgets and solve verified own-aux/aggregate-budget guards before code/scoring.'},
 'parent_file_bindings':{n:sha256_file(root/n) for n in names},'ledger_prefixes':prefixes,'B_wallet_at_freeze':wallet,
 'forbidden':['research fit','EXP/registration/scoring','active loader/cohort/config/schema modification','coordinate/name output','unknown-row rescue','filter/replacement','futurewriters6-15/21-30','Data_Table','WT8-9','source fit replay','external model/API','schedule change','retry','protected7tickets/47000s spending','original limit expansion'],
 'goal_status':'ACTIVE; second-family scientific comparison, replications, fresh finals and prototype unfinished'}
atomic_write_json(path,plan)
append_jsonl(root/'research/events.jsonl',{'event':'maintenance_preparation_preregistered','created_at':utc_now(),'cycle':332,'plan_id':identity,'plan_sha256':sha256_file(path),'before_implementation_and_new_native_bytes':True})
auxiliary_reserve(root,identity,900)
print({'plan_sha256':sha256_file(path),'aux_reserved':900,'research_fit':0,'EXP':0,'fixed_samples':1830},flush=True)
