from pathlib import Path
from copy import deepcopy
from nextai_autoresearch.utils import atomic_write_json,load_json,sha256_file,utc_now
from nextai_autoresearch.ledger import append_jsonl,read_jsonl
from nextai_autoresearch.research_program import status
root=Path.cwd();studyrel='research/plans/HAR01-INDEPENDENT-REPLICATION-V1.json';taskrel='research/plans/HAR01-REPLICATION-TASK-V1.json';authrel='research/laboratory/HAR01-REPLICATION-PREPARATION-AUTHORITY-V1.json';assert not (root/studyrel).exists()
wallet=status(root);assert wallet['stage_b_registration_attempts_used']==1 and wallet['protected_future_compute_seconds']==47000 and wallet['unreserved_fit_seconds_remaining']>=47000
parent=load_json(root/'research/plans/HAR01-FROZEN-SOURCE-SCREEN-V1.json');task=deepcopy(load_json(root/'research/plans/HAR01-NATIVE-TASK-CONTRACT-V1.json'))
subjects=[{'unit':i,'train_subject':i+6,'dev_subject':i+21,'source_unit':i} for i in range(5)]
task.update(id='HAR01-REPLICATION-TASK-V1',created_at=utc_now(),parent_task_sha256=sha256_file(root/'research/plans/HAR01-NATIVE-TASK-CONTRACT-V1.json'),parent_screen_result_sha256=sha256_file(root/'research/results/EXP-20261005-0007.json'),scope='independent target replication only T6-10/D21-25; all other future raw signals closed',acquisition_manifest_path='research/data_manifests/HAR01-REPLICATION-ACQUISITION-V1.json',dataset_path='research/data/har01_replication_v1/replication.npz',publisher_path='research/data/har01_native_v1/publisher.zip')
task['independence']['screen']=subjects;task['intake']['parse_numeric_signals_only_for_screen_subjects']=list(range(6,11))+list(range(21,26));task['independence']['source_units_reused_as_fixed_controls']=True
atomic_write_json(root/taskrel,task)
auth={'id':'HAR01-REPLICATION-PREPARATION-AUTHORITY-V1','created_at':utc_now(),'program_id':wallet['id'],'program_contract_path':'research/plans/NEXTAI-TRANSFER-PROTOTYPE-PROGRAM-V1.json','program_contract_sha256':sha256_file(root/'research/plans/NEXTAI-TRANSFER-PROTOTYPE-PROGRAM-V1.json'),'study_path':studyrel,'stage':'independent_replication','stage_slot':0,'preparation_seconds_cap':1200,'whole_stage_seconds_cap':6000,'protected_other_registration_attempts':6,'protected_other_compute_seconds':41000,'human_authorization':'2026-10-06: Resume goal. Up to1200 seconds from existing6000 first independentHARreplication for preregistration,minimalharness,owncostaccounting andclonetests alsoBEFOREEXP. Prepcountswithin6000total;Bnotincreased/historynotreset;other6/41000protected. FreshHAR T6-10/D21-25allowed;allotherfuturedata closed;same model recipe5pairs3scales metrics thresholds. No retry,source refit,newarchitecture,WT8-9,externalmodels/API,schedulechange.','wallet_before':wallet,'before_new_code_or_future_HAR_signal':True}
atomic_write_json(root/authrel,auth)
plan=deepcopy(parent);plan.update(id='HAR01-INDEPENDENT-REPLICATION-V1',created_at=utc_now(),cycle=337,stage='independent_replication',cohort='har01_native_memory_v2',task_contract_path=taskrel,task_contract_sha256=sha256_file(root/taskrel),study_started_at='2026-10-06T14:56:00Z',study_deadline_at='2026-10-06T16:36:00Z',parent_study_path='research/plans/HAR01-FROZEN-SOURCE-SCREEN-V1.json',parent_study_sha256=sha256_file(root/'research/plans/HAR01-FROZEN-SOURCE-SCREEN-V1.json'),preparation_authority_path=authrel,preparation_authority_sha256=sha256_file(root/authrel),preparation_deadline_at='2026-10-06T15:16:00Z',preparation_charge_id='HAR01-REPLICATION-preparation-V1',preparation_seconds_cap=1200,whole_stage_seconds_cap=6000,auxiliary_charge_ownership={'allowed_ids':['HAR01-REPLICATION-preparation-V1','HAR01-REPLICATION-controller-V1'],'bound_to_exact_study_sha256':True,'all_pending_reserved_or_final_charged_once':True,'no_prefix_credit':True},implementation_rule='New cohort/intake/harness binding only. Exact scientific recipe,methods,metrics,grids and gates immutable against parent; versioned loader/benchmark reuses unchanged HARcore. Old cohorts unchanged. Separate positive/negative public syntheticfixtures before one freshnativeintake. Fixture/intakefailure stops unstarted scope. Registrationonly afterindependentclone conformance,integrity/preflight/readiness. OneEXP maximum.',clock_cap_policy='Full stage6000wallseconds including failures/admin; preparation1200max. Worker enclosingJob hard3600s fullwall inclrunner/fit startup/teardown, no role retry. Auxiliarytotal2400 includesprep1200+controller/archive/report1200. Fullworkers charged from preservedexecutions; uncoveredboundedjob overhead chargedaux, no doublecount. Stop allunstarted at anyfailure/deadline/cap.',hypothesis_interpretation='Independent replication of previouslynegative exactHARrecipe; not positivequalification prerequisite, notoldtargetrescue. New target subjects/nonces/seeds with actualsamefixedsource states; no priorresults pooled. Each independent targetpair is CIunit. Outcome canremainnegative orchange; unchanged decision gates.',protected_other_registration_attempts=6,protected_other_compute_seconds=41000)
plan['data']['screen_subjects']=subjects;plan['matrix']['seeds']=[337060,337061,337062,337063,337064]
plan['resources'].update(fit_seconds_study_cap=3600,auxiliary_test_seconds_cap=2400,startup_charge_included_seconds=0,enclosing_worker_job_seconds_cap=3600,enclosing_worker_job_closing_reserve_seconds=15)
plan['parent_bindings']={p:sha256_file(root/p) for p in ['AGENTS.md','research/plans/NEXTAI-TRANSFER-PROTOTYPE-PROGRAM-V1.json','research/results/EXP-20261005-0007.json','src/nextai_autoresearch/har01_task.py','src/nextai_autoresearch/candidates/har01_core.py','src/nextai_autoresearch/benchmarks/har01_native_memory_v1.py','src/nextai_autoresearch/har01_analysis.py','research/laboratory/EXP-20261005-0006-fitted-state-publication-V1.json']}
atomic_write_json(root/studyrel,plan);digest=sha256_file(root/studyrel)
append_jsonl(root/'research/events.jsonl',{'event':'research_program_scoped_preparation_authorized','created_at':utc_now(),'program_id':wallet['id'],'study_path':studyrel,'study_sha256':digest,'authority_path':authrel,'authority_sha256':sha256_file(root/authrel),'stage':'independent_replication','stage_slot':0,'cap':1200,'whole_stage_cap':6000,'human_authorized':True})
append_jsonl(root/'research/events.jsonl',{'event':'research_program_study_frozen','created_at':utc_now(),'program_id':wallet['id'],'study_path':studyrel,'study_sha256':digest})
append_jsonl(root/'research/events.jsonl',{'event':'research_program_aux_fit_reserved','created_at':utc_now(),'program_id':wallet['id'],'charge_id':plan['preparation_charge_id'],'seconds_cap':1200,'study_path':studyrel,'study_sha256':digest,'authority_path':authrel,'authority_sha256':sha256_file(root/authrel),'explicit_scoped_preparation_bootstrap':True})
print({'study':studyrel,'sha256':digest,'task_sha256':sha256_file(root/taskrel),'authority_sha256':sha256_file(root/authrel),'prep_deadline':plan['preparation_deadline_at']},flush=True)
