from pathlib import Path
from nextai_autoresearch.utils import atomic_write_json,sha256_file,utc_now,load_json
from nextai_autoresearch.ledger import append_jsonl
from nextai_autoresearch.research_program import auxiliary_charge
root=Path.cwd();identity='HAR01-NEGATIVE-REPLICATION-FEASIBILITY-V1';planpath=root/f'research/plans/{identity}.json';plan=load_json(planpath)
assert all(sha256_file(root/p)==digest for p,digest in plan['parent_bindings'].items())
old=load_json(root/'research/plans/HAR01-FROZEN-SOURCE-SCREEN-V1.json');oldcap=old['resources']['fit_seconds_study_cap']+old['resources']['auxiliary_test_seconds_cap'];assert oldcap==12500
proof={'created_at':utc_now(),'scope':'read-only feasibility; no executable scientific code','stage_after_full_charge_unprotected_seconds':30.4497597999289,'planned_replication_only_protected_release_seconds':6000,'planned_replication_max_total_reservation':6030.449759799929,'old_worker_plus_aux_cap':oldcap,'old_cap_shortfall':oldcap-6030.449759799929,'existing_check_strict_positive_timeout_plus_closing40_minimum_cap':40,'existing_controller_before_registration_aux_cap':900,'existing_paths_scope_and_sources_sha256':{p:sha256_file(root/p) for p in ['schemas/experiment_plan.schema.json','src/nextai_autoresearch/har01_task.py','src/nextai_autoresearch/research_program.py','scripts/run_har01_check.py','scripts/run_har01_experiment.py','scripts/check_har01_readiness.py']},'blocking_facts':['HAR schema fixes oldstudy/hash/task and9000fit cap','loader fixedoldmanifest andsubjects1-5/16-20; nofresh6-10/21-25support','readiness fixesoldstudy/intake,1361cases andalreadyconsumedproofoutputs','checkrequires timeout+40<=cap;40>30.44976','controllerreserves900auxbeforeregister;900>30.44976','auxreservecannotreleaseplannedstageown6000beforeticket','ticketconsumedBEFOREreserve/schema checks; nofailedtrialregister'],'independent_review':'muc_readonly read-only PASS; no tests imports or raw reads','metadata_read_failure_preserved':'Initialread used nonexistent src/nextai_autoresearch/data/har01_task.py;rg locatedcorrectmodule; no scientifictest or data attempt; includedcost','scientific_gate_changes':False,'new_native_reads':0,'fit':0,'EXP':0,'registration':0,'tests':0,'retry':False,'decision':'NO EXECUTION under current bindings and auxiliary preparation allowance; prospective new harness/ownership preparation funding required','full_goal':'ACTIVE/INCOMPLETE'}
proofpath=root/'research/reviews/HAR01-NEGATIVE-REPLICATION-FEASIBILITY-V1.json';atomic_write_json(proofpath,proof)
auxiliary_charge(root,identity,200)
receipt={'created_at':utc_now(),'id':identity,'plan_sha256':sha256_file(planpath),'proof_sha256':sha256_file(proofpath),'decision':proof['decision'],'charged_seconds':200,'clock_start':'2026-10-06T04:08:00Z','deadline':'2026-10-06T04:11:20Z','fit':0,'EXP':0,'registration':0,'tests':0,'new_native_reads':0,'retry':False,'protected_tickets':7,'protected_seconds':47000,'unprotected_B_seconds_remaining':30.4497597999289,'prior_turn_classification':'PROGRESS through actual known-file evidence','this_scope':'verified budget/schema/loader/readiness obstruction; noscientificprogress','full_goal_status':'ACTIVE/INCOMPLETE'}
out=root/'research/laboratory/HAR01-NEGATIVE-REPLICATION-FEASIBILITY-COMPLETION-V1.receipt.json';atomic_write_json(out,receipt);append_jsonl(root/'research/events.jsonl',{'event':'maintenance_preparation_closed','created_at':utc_now(),'cycle':336,'plan_id':identity,'receipt_sha256':sha256_file(out),'decision':proof['decision'],'fit':0,'EXP':0})
(root/'research/analyses/HAR01-CYCLE336-NEGATIVE-REPLICATION-FEASIBILITY-V1.md').write_text('''# Cykl336 — wykonalność niezależnej negatywnej replikacji HAR

**Decyzja: NO EXECUTION z istniejącym harness. Cel pełny pozostaje nieukończony.**

Kontrakt B dopuszcza negatywny wynik; nie wymaga dodatniego screening przed niezależną replikacją. Nowa replikacja pięciu świeżych sparowanych target units przy niezmienionej naukowej recepturze jest sensowną alternatywą do rescue ASM. Obecny program zwalnia jej własne6000s/1ticket na etapie registration, zachowując pozostałe6tickets/41000s. Przed registration auxiliary guard chroni jednak całe7/47000s. Po pełnym koszcie tego audytu pozostaje30.4497597999289s niechronionych.

Nie ma gotowej ścieżki do świeżej replikacji. Schema7474/7742 wymusza stary9000s worker cap, study/hash/task; wraz3500aux daje12500s wobec maksymalnej6030.44976s rezerwacji nowej replikacji. har01_task.py54–74 wiąże loader ze starym manifestem iT1–5/D16–20. check_har01_readiness.py17–47 wymaga starego study/intake,1361cases i starych jednorazowych receipts. run_har01_check.py33 wymaga timeout+40<=cap, więc nawet jego minimalny cap przekracza pozostałe30.45s. run_har01_experiment.py27 rezerwuje900aux przed registration, co obecny auxiliary guard odrzuci. research_program.py475 zapisuje ticket przed reserve/schema checks: próbny registration spaliłby rejestrację. Nie wykonano go.

Zmniejszenie deklaracji cap nie zmienia rzeczywistych potrzeb ani istniejących schema bindings. Stary screen nie może być wykonany ponownie, a stare tests/intake/readiness nie dowodzą gotowości świeżej kohorty. Potrzebne są nowa prerejestracja, cohort bindings, loader/schema/readiness i hardbounded budżet z audytem własnych kosztów, przed przyszłymi danymi i z conformance w klonie. Nie twierdzimy, że niewykonalna jest każda możliwa implementacja; wykazaliśmy niewykonalność istniejącej ścieżki z jej konkretnymi limitami.

Opcje wymagające decyzji o finansowaniu: przydzielić część własnych6000s przyszłej replikacji także na jej przygotowanie przed registration, z jawnie hash-bound ownership, bez wydatków na screen/ASM i bez naruszania41000s pozostałych etapów; albo dodatkowy ograniczony budżet na nowe przygotowanie/rodzinę. Nie wolno po cichu przekierować chronionych środków, wyzerować historii, źródeł lub kosztów. Prototyp5000s nie jest shortcut: AGENTS217/230 wymaga niezależnej replikacji i świeżych targetfinals przed nim. WynikiA same-law nie są targetfinalB.

W tym zakresie:200s od04:08 do04:11:20Z, obejmujące startup, prerejestrację, metadata/code reads, independent audit, koszt administracyjnego błędnego path i zamknięcie/publikację. Test0, fit0, EXP0, registration0, newnative0. Protected7/47000s zachowane. Wcześniejsze A resolution, HARnegative, ASMintakeinvalidity, MUCnegative i wszystkie failure/cost receipts pozostają bez zmian.

Brakujące deliverables pełnego celu: druga niezależna naukowa rodzina; niezależne replikacje i świeże targetfinals B przy co najmniej5pairedunits/3scales; lokalny evidence-selected fact/source/update/UNKNOWNprototype; pełne koszty i uncertainty tych etapów. Ten audyt nie jest ukończeniem tych wymagań ani nowym EXP.
''',encoding='utf-8',newline='\n')
print(receipt,flush=True)
